---
title: "HCP Autocorrelation"
author: "Damon Pham"
date: "02/01/2022"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------

roxygen2::roxygenize("/Users/ddpham/Documents/GitHub/gifti") # options() patch

# Packages
# install.packages("ciftiTools")
library(ciftiTools)
stopifnot(packageVersion("ciftiTools") >= "0.8.0")

# devtools::install_github("mandymejia/BayesfMRI", "1.9")
# library(BayesfMRI)
roxygen2::roxygenize("/Users/ddpham/Documents/GitHub/BayesfMRI")
stopifnot(packageVersion("BayesfMRI") >= "0.1.9")

# Directories
dir_data <- "/Volumes/Lab_Data_Drive/data"
dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper"
ciftiTools.setOption("wb_path", "/Users/ddpham/Desktop/workbench")

# Where to save the first part of this analysis (this script)
dir_ac1 <- file.path(dir_project, "AC1")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

# Remove subjects excluded from Fatma's original analysis.
subjects_rm <- c(
  144226, 627549,
  660951, 169343,
  177746
)
# 877168 has missing data for Language; see 0_Check
subjects <- setdiff(subjects, subjects_rm)

tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")

missing <- readRDS("0_MissingFiles.rds")
missing[128,"emotion"] <- 3 #Truncated CIFTI

TR <- .72

resamp_res <- 6000
surf_FWHM <- 6

cii_tmp_r <- paste0(tempfile(),".r.dtseries.nii")
cii_tmp_s <- paste0(tempfile(),".s.dtseries.nii")

surfL_rr_fname <- resample_surf(
  ciftiTools.files()$surf["left"], 
  paste0(tempfile(), ".L.surf.gii"), resamp_res = resamp_res
)
surfR_rr_fname <- resample_surf(
  ciftiTools.files()$surf["right"], 
  paste0(tempfile(), ".R.surf.gii"), resamp_res = resamp_res
)

T_trunc_FUN <- function(t){round(t/4)} # (Anderson, 1983)

# Hello!
```

```{r}
iters <- expand.grid(test=c(TRUE, FALSE), acquisition=c("LR", "RL"), subject=subjects)

time <- Sys.time()
for (task in tasks) {

  if (task %in% c("language", "social")) { next }

  TASK <- toupper(task); Task <- tools::toTitleCase(task)
  cat(Task, "---------------------------------------------------------------\n")

  for (ii in seq(nrow(iters))) {
    
    # Prep ------------------------------------------------------------------------------
    # Get iteration info. 
    test <- iters[ii, "test"]
    acquisition <- as.character(iters[ii, "acquisition"])
    subject <- iters[ii, "subject"]
    ii_name <- paste0(subject, "_", acquisition, ifelse(test, 1, 2))
    cat(ii_name, "\t")

    # Skip if missing or completed already.
    # if (missing[ii,task] > 0) { cat("Missing data.\n"); next}
    ac_fname <- file.path(dir_ac1, task, paste0(ii_name, "_pw.rds"))
    if (!dir.exists(dirname(ac_fname))) { dir.create(dirname(ac_fname)) }
    if (file.exists(ac_fname)) { cat("Done.\n"); next }
    cat("\n")

    ## Get the data sub-directory for this iteration.
    dir_data_ii <- file.path(dir_data, paste0("HCP_", TASK))
    if (!test) { dir_data_ii <- file.path(dir_data_ii, "retest") }
    fname_prefix <- paste("tfMRI", TASK, acquisition, sep="_")
    dir_data_ii <- file.path(dir_data_ii, subject, "MNINonLinear/Results", fname_prefix)

    ## Get the number of timepoints.
    T_ <- switch(task,
      emotion = 176,
      gambling = 253,
      language = 316,
      motor = 284,
      relational = 232,
      social = 274
    )
    T_trunc <- T_trunc_FUN(T_)

    ## Get the task event files.
    enames <- switch(task,
      emotion = c("fear", "neut"), 
      gambling = c("loss_event", "neut_event", "win_event"),
      language = as.character(
        outer(c("present", "question", "response"), c("math", "story"), paste, sep="_")
      ),
      motor = c("cue", "lf", "lh", "rf", "rh", "t"),
      relational = c("match", "relation"),
      social = c("mental", "rnd", "mental_resp", "other_resp")
    )
    fnames <- file.path("EVs", paste0(enames, ".txt"))

    ## Get the CIFTI file and movement regressors.
    fnames <- c(
      paste0(fname_prefix, "_Atlas.dtseries.nii"), "Movement_Regressors.txt", fnames
    )
    ## Full file paths
    fnames <- file.path(dir_data_ii, fnames)

    # Read in files --------------------------------------------------------------------
    cat("Reading in files, and centering & scaling the CIFTI data.\n")
    
    # Read in CIFTI (VxT).
    # Smooth, then resample. (Try the opposite order? Slower but better?)
    # Then read it in. 
    cii <- fnames[1]
    cat("Resampling... ")
    resample_cifti(cii, cii_tmp_r, resamp_res=resamp_res)
    cat("Smoothing... ")
    smooth_cifti(cii_tmp_r, cii_tmp_s, surf_FWHM=surf_FWHM)
    cat("Reading in.\n")
    cii <- ciftiTools::read_xifti(cii_tmp_s)
    file.remove(cii_tmp_r); file.remove(cii_tmp_s)

    # Mask out low-mean vertices from CIFTI.
    #   Problem for Gambling 662551_LR1
    cii_const <- rowMeans(abs(as.matrix(cii))) < 1
    if (any(cii_const)) { 
      cat("Warning:", sum(cii_const), "voxels have a mean < 1. Removing these.\n")
      q <- as.matrix(cii)
      q[cii_const,] <- NA
      cii <- newdata_xifti(cii, q)
      cii <- move_to_mwall(cii)
    }

    # Center and scale to units of percent change for each voxel timecourse.
    # `scale_timeseries` transposes `cii`, so we transpose back. [TO DO]: fix this
    # cii <- newdata_xifti(cii, t(BayesfMRI::scale_timeseries(cii, transpose=FALSE)))
    
    # Read in motion data (Tx12)
    # First six is realignment params, second six are derivatives.
    rp <- scale(as.matrix( read.table(fnames[2]) ))

    # Read in events.
    #   For each event file, get the first two columns.
    #   The first is the onset, the second is the duration.
    events <- lapply(
      fnames[seq(3,length(fnames))], 
      function(x){
        # Use `try` because some event files are empty.
        out <- try(read.table(x, header=FALSE))
        if (inherits(out, "try-error")) {
          return(NULL)
        } else {
          return(out[,seq(2),drop=FALSE])
        }
      }
    )
    names(events) <- enames
    events <- events[!vapply(events, is.null, FALSE)]
    
    # Calculate model & residuals -----------------------------------------------------
    cat("Calculating HRFs, running the GLMs, and obtaining their residuals.\n")
    # hrf <- scale(BayesfMRI::make_HRFs(events, 0.72, T_))
    # hrfdt <- scale(rbind(0, diff(hrf)))
    # dtb <- scale(seq(T_))
    # dtb <- scale(cbind(dtb, dtb^2))
    # design <- cbind(1, rp, dtb, hrf)
    # resids <- list(
    #   a = BayesfMRI::nuisance_regression(cii, cbind(design)),
    #   b = BayesfMRI::nuisance_regression(cii, cbind(design, hrfdt))
    # )
    resids <- vector("list", 2)
    names(resids) <- c("ar6_HRF", "ar6_dHRF")
    # resids <- vector("list", 4)
    # names(resids) <- c("ar0_HRF", "ar6_HRF", "ar0_dHRF", "ar6_dHRF")
    # resids$ar0_HRF <- BayesGLM_cifti(
    #   cii, onsets=events, Bayes=FALSE, TR=TR, resamp_res = NULL,
    #   nuisance=rp, nuisance_include=c('drift'),
    #   ar_order=0
    # )
    resids$ar6_HRF <- BayesGLM_cifti(
      cii, onsets=events, Bayes=FALSE, TR=TR, resamp_res = NULL,
      nuisance=rp, nuisance_include=c('drift'),
      surfL_fname=surfL_rr_fname, surfR_fname=surfR_rr_fname,
      ar_order=6, ar_smooth=6
    )
    # resids$ar0_dHRF <- BayesGLM_cifti(
    #   cii, onsets=events, Bayes=FALSE, TR=TR, resamp_res = NULL,
    #   nuisance=rp, nuisance_include=c('drift','dHRF'),
    #   ar_order=0
    # )
    resids$ar6_dHRF <- BayesGLM_cifti(
      cii, onsets=events, Bayes=FALSE, TR=TR, resamp_res = NULL,
      nuisance=rp, nuisance_include=c('drift','dHRF'),
      surfL_fname=surfL_rr_fname, surfR_fname=surfR_rr_fname,
      ar_order=6, ar_smooth=6
    )
    resids <- lapply(resids, function(rr){
      rbind(
        rr$GLMs_classical$cortexL$single_session$resids,
        rr$GLMs_classical$cortexR$single_session$resids
    )})
    
    # In case voxels became constant after nuisance regression
    # Does this actually happen?
    resids_const <- setNames(rep(list(cii_const), length(resids)), names(resids))
    for (rr in seq(length(resids))) {
      resid_const <- colSums(abs(resids[[rr]])) < 1e-8
      if (any(resid_const)) { 
        cat("Warning:", sum(resid_const), "voxels became constant after", names(resids)[rr], "nuisance regression. Removing these.\n")
        resids_const[[rr]][!resids_const[[rr]]] <- resid_const
        resids[[rr]] <- resids[[rr]][!resid_const,]
      }
    }
    
    # Formatting
    resids_const <- lapply(resids_const, which)
    # [TO DO]: Resolve non-zero mean issue for pw.
    # stopifnot(all(abs(do.call(cbind, lapply(resids, rowMeans))) < 1e-8))
    # resids <- lapply(resids, function(x){x - rowMeans(x)})

    # Estimate AC statistics & save --------------------------------------------------
    cat("Estimating AC statistics.\n")
    #out <- lapply(resids, function(x){ apply(x, 2, get_ac_stats) })
    out <- setNames(vector("list", length(resids)), names(resids))
    for (rr in seq(length(resids))) {
      cat("\t", names(out)[rr])
      out[[rr]] <- setNames(vector("list", 6), c("var", "aci", "acit", "ar6c", "ar6v", "aic"))
      resid <- resids[[rr]] # VxT?
      out[[rr]]$var <- rowVars(resid)
      rr_acf <- apply(resid, 1, stats::acf, lag.max=T_-1, plot=FALSE, demean=FALSE)
      rr_acf <- do.call(rbind, lapply(rr_acf, function(x){as.numeric(x$acf)}))
      out[[rr]]$aci <- rowSums(rr_acf^2)
      out[[rr]]$acit <- rowSums(rr_acf[,seq(T_trunc)]^2)
      # out[[rr]]$acf1 <- rr_acf[,2]
      # out[[rr]]$acf1 <- apply(resid[,seq(T_-1)] * resid[,seq(2, T_)], 1, mean) / out[[rr]]$var # [TO DO]: not exactly same. why?
      rr_ar6 <- apply(resid, 1, function(v){ q <- stats::ar.yw(v, aic=FALSE, order.max=6, demean=FALSE); c(q$ar[1], q$var.pred) })
      out[[rr]]$ar6c <- rr_ar6[1,]
      out[[rr]]$ar6v <- rr_ar6[2,]
      out[[rr]]$aic <- apply(resid, 1, function(v){ stats::ar.yw(v, aic=TRUE, order.max=10, demean=FALSE)$order })
    }
    
    # Formatting
    # out <- lapply(out, function(x){ list(z=do.call(cbind, x[names(x) != "aic"]), aic=x$aic) })
    if (sum(do.call(c, resids_const)) > 0) { out$const <- resids_const }
    
    cat("\nSaving.\n\n")
    saveRDS(out, ac_fname)
    
    print(Sys.time() - time); time <- Sys.time()
  }
}
```
