---
title: "Aggregate HCP AC Sources Results"
author: "Damon Pham"
date: "02/01/2022"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------

# Directories
dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Mac Pro and Damon laptop
# dir_project <- "G:/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Damon PC

# Where to save the first part of this analysis (this script)
dir_ac1 <- file.path(dir_project, "AC1")
dir_agg <- file.path(dir_project, "AC1_agg")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

# Remove subjects excluded from Fatma's original analysis.
subjects_rm <- c(
  144226, 627549,
  660951, 169343,
  177746
)
# 877168 has missing data for Language; see 0_Check
subjects <- setdiff(subjects, subjects_rm)

# tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")
tasks <- c("emotion", "gambling", "motor", "relational")

# missing <- readRDS("0_MissingFiles.rds")
# missing[128,"emotion"] <- 3 #Truncated CIFTI

nVox <- 10578
```

```{r}
theVars <- list(
  task=tasks,
  subject=paste0("s", subjects),
  acquisition=c("LR", "RL"), 
  test=c("test", "retest"),
  nreg=c("ar0_HRF", "ar6_HRF", "ar0_dHRF", "ar6_dHRF"),
  vox=seq(nVox)
)

iters <- expand.grid(test=c(TRUE, FALSE), acquisition=c("LR", "RL"), subject=subjects)

# Damon 2/1/22
#   some is.na for emotion
#   none is.na for gambling

for (meas in c("var", "aci", "acit", "ar6c", "ar6v", "aic")) {
  cat(meas, "----------------\n")
  
  agg <- array(dim=vapply(theVars, length, 0))
  dimnames(agg) <- theVars
  dimnames(agg)[6] <- list(NULL)
  agg_fname <- file.path(dir_agg, paste0(meas, ".rds"))
  if (file.exists(agg_fname)) { next }
  
  # Add these results.
  time <- Sys.time()
  for (task in tasks) {
    cat(task, "\n")
  
    for (ii in seq(nrow(iters))) {
      cat(ii, "\t")
      # Get AC results.
      # if (missing[ii,task] > 0) { next }
      test <- iters[ii, "test"]
      acquisition <- as.character(iters[ii, "acquisition"])
      subject <- iters[ii, "subject"]
      ii_name <- paste0(subject, "_", acquisition, ifelse(test, 1, 2))

      # Without prewhitening ---------------------------------------------------
      ac_fname <- file.path(dir_ac1, task, paste0(ii_name, ".rds"))
      ac <- readRDS(ac_fname)
      if ("const" %in% names(ac)) {
        stop() # Need to check this code.
        # Get voxel mask. (Some voxels were constant and so do not have results.)
        # out <- matrix(nrow=length(theVars$nreg), ncol=nVox)
        # for (nn in seq(length(theVars$nreg))) { out[nn, !ac$const[[nn]]] <- ac[[nn]][[meas]] }
        # agg[task, paste0("s", subject), acquisition, ifelse(test, "test", "retest"),,] <- out
      } else {
        agg[task, paste0("s", subject), acquisition, ifelse(test, "test", "retest"),c(1,3),] <- do.call(rbind, lapply(ac, function(x){x[[meas]]}))
      }

      # With prewhitening ------------------------------------------------------
      ac_fname <- file.path(dir_ac1, task, paste0(ii_name, "_pw.rds"))
      ac <- readRDS(ac_fname)
      if ("const" %in% names(ac)) {
        stop()
      } else {
        agg[task, paste0("s", subject), acquisition, ifelse(test, "test", "retest"),c(2,4),] <- do.call(rbind, lapply(ac, function(x){x[[meas]]}))
      }
    }
    print(Sys.time() - time); time <- Sys.time()
  }
  saveRDS(agg, agg_fname)
}
```

Quick plots

```{r, eval=FALSE}
xii <- read_xifti("/Volumes/GoogleDrive/My Drive/MEJIA_LAB-Damon/ciftiToolsPaper/rfMRI.dtseries.nii", idx=1)
xii <- resample_xifti(xii, resamp_res=6000)

for (meas in c("var", "aci", "acit", "ar6c", "ar6v", "aic")) {
  mtitle <- switch(meas,
    var = "residual variance",
    aci = "ACI",
    acit = "ACI truncated to T/4",
    ar6c = "AR(6) model, first coefficient",
    ar6v = "AR(6) model, estimated variance",
    aic = "AIC AR(p) model order"
  )
  zlim <- switch(meas,
    var = c(0, 3),
    aci = c(1, 2),
    acit = c(1, 2),
    ar6c = c(0, .25),
    ar6v = c(0, 3),
    aic = c(0, 2)
  )
  cat(meas, "\n")
  agg <- readRDS(file.path(dir_agg, paste0(meas, ".rds")))
  xii <- newdata_xifti(xii, apply(agg, length(dim(agg)), mean))
  plot(
    xii, title=mtitle, zlim=zlim, 
    fname=file.path(dir_project, "Plots", paste0(meas, "_grandMean.png"))
  )
}
```
