---
title: "3_LMM_Thesis_Replicate_FP"
author: "fatma parlak"
date: "2/7/2022"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------
library(reshape2)
library(lme4)

# Directories
dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Mac Pro
# dir_project <- "G:/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Damon personal

# Where to save the first part of this analysis (this script)
dir_agg <- file.path(dir_project, "AC1_agg")
dir_lmm <- file.path(dir_project, "AC1_lmm")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

# Remove subjects excluded from Fatma's original analysis.
subjects_rm <- c(
  144226, 627549,
  660951, 169343,
  177746
)
# 877168 has missing data for Language; see 0_Check
subjects <- setdiff(subjects, subjects_rm)

# tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")
tasks <- c("emotion", "gambling", "motor", "relational")

missing <- readRDS("0_MissingFiles.rds")
missing[128,"emotion"] <- 3 #Truncated CIFTI

nVox <- 10578
```

```{r}
iters <- expand.grid(
  pw_FWHM=c(5, Inf), 
  pw_order=c(0, 1, 3, 6),
  meas=c( "aci", "ar6c", "var", "acf1", "ar6v")
)

time <- Sys.time()

for (ii in seq(length(iters))) {
  
  # Prep ------------------------------------------------------------------------------
  # Get iteration info. 
  pw_FWHM <- iters[ii, "pw_FWHM"]
  pw_order <- iters[ii, "pw_order"]
  meas <- iters[ii, "meas"]
  
  out_fname <- file.path(dir_lmm, paste0(meas, "_pwFWHM-", pw_FWHM, "_pwO-", pw_order, ".rds"))
  if (file.exists(out_fname)) { next }
  
  dat <- readRDS(file.path(dir_agg, paste0(meas, ".rds")))
  dat <- dat[,,,,as.character(pw_FWHM),as.character(pw_order),,]
  
  # 9 rows for string the Fixed Effects (E, G, M, R, RL, dHRF, dHRF*G, dHRF*M, dHRF*R) 
  fixed_fx <- array(NA, dim= c(nVox, 9)) 
  # 37 rows for storing Random Effect's std. dev. 
  # [(8 for diagonal + (7*8)/2 for off-diagonals] + 1 for residual 
  var_cor <- array(NA, dim = c(nVox, 37))

  for (vv in seq(nVox)) {
    print(vv)
    dat_vv <- dat[,,,,,vv]
    df_vv <- reshape2::melt(dat_vv, varnames=names(dimnames(dat_vv)))
    
    df_vv$cHRF <- (df_vv$HRF=="HRF")

    q <- lme4::lmer(value ~ -1 + task + acquisition + cHRF + task*cHRF  + (-1 + task*cHRF | subject) , data = df_vv)
    fixed_fx[vv,] <- c(lme4::fixef(q))
    var_cor[vv,] <- c((as.data.frame(lme4::VarCorr(q))$sdcor))  # 4*2 std + (7*8)/2 corr + 1 residual

    if (vv == 1) {
      colnames(fixed_fx) <- names(lme4::fixef(q))
      colnames(var_cor) <- apply(as.data.frame(lme4::VarCorr(q))[,seq(3)], 1, paste, collapse="-")
    }
  }  

  saveRDS(list(fixed_fx = fixed_fx, var_cor = var_cor), out_fname)
  
  cat("\n")
  print(Sys.time() - time); time <- Sys.time()
}
```
