---
title: "AC Sources Model"
author: "Damon Pham"
date: "01/01/2021"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------

# Packages
## `lme4`: multilevel modeling
library(lme4)
stopifnot(packageVersion("lme4") >= "1.1.27.1")

# Directories
# dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Mac Pro
dir_project <- "G:/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Damon personal

# Where the AC results were saved
dir_agg <- file.path(dir_project, "AC1_agg")
dir_lm <- file.path(dir_project, "AC1_lm2")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

# Remove subjects excluded from Fatma's original analysis.
subjects_rm <- c(
  144226, 627549,
  660951, 169343,
  177746
)
# 877168 has missing data for Language; see 0_Check
subjects <- setdiff(subjects, subjects_rm)

# tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")
tasks <- c("emotion", "gambling", "motor", "relational")

missing <- readRDS("0_MissingFiles.rds")
missing[128,"emotion"] <- 3 #Truncated CIFTI

nVox <- 10578
```


```{r}
time <- Sys.time()
for (meas in c("var", "aci", "acit", "ar6c", "ar6v", "aic")) {
  cat(meas, "\t")

  fixed_fx <- matrix(nrow=nVox, ncol=9)
  var_cor <- matrix(nrow=nVox, ncol=11) # lm: 22
  is_singular <- vector("logical", nVox)
  
  dat <- readRDS(file.path(dir_agg, paste0(meas, ".rds")))
  # df <- do.call(expand.grid, dimnames(dat)[rev(seq(length(dim(dat))-1))])
  # df$ar6 <- grepl("ar6", df$nreg)
  # df$dHRF <- grepl("dHRF", df$nreg)
  for (vv in seq(nVox)) {
    if (vv %% 2000 == 0) { cat(vv, "\t") }
    # df$meas <- as.vector(dat[,,,,,vv])
    dat_vv <- dat[,,,,,vv]
    df_vv <- reshape2::melt(dat_vv, varnames=names(dimnames(dat_vv)))
    df_vv$dHRF <- 1 - as.numeric(grepl('dHRF', df_vv$nreg)) #0 = dHRF included (baseline), 1 = dHRF not included
    df_vv$ar6 <- 1 - as.numeric(grepl('ar6', df_vv$nreg)) #0 = motion regression (baseline), 1 = no motion regression
    q <- lme4::lmer(
      value ~ -1 + task + task:(dHRF + ar6) + acquisition + ((-1 + task)|subject), 
      data=df_vv
    )
    fixed_fx[vv,] <- fixef(q)
    var_cor[vv,] <- as.data.frame(VarCorr(q))$sdcor
    is_singular[vv] <- isSingular(q)
    if (vv == 1) { 
      colnames(fixed_fx) <- names(fixef(q))
      colnames(var_cor) <- apply(
        as.data.frame(VarCorr(q))[,seq(3)], 
        1, paste, collapse="-"
      )
    }
  }
  saveRDS(
    list(fixed_fx=fixed_fx, var_cor=var_cor, is_singular=is_singular), 
    file.path(dir_lm, paste0(meas, ".rds"))
  )
  
  cat("\n")
  print(Sys.time() - time); time <- Sys.time()
}
```
