---
title: "AC Sources Model"
author: "Damon Pham"
date: "01/01/2021"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------

# Packages
## `lme4`: multilevel modeling
library(lme4)
stopifnot(packageVersion("lme4") >= "1.1.26")
## CIFTI
library(ciftiTools)
stopifnot(packageVersion("ciftiTools") >= "0.2.0")
ciftiTools.setOption("wb_path", "../workbench")

# Directories
dir_data <- "/Users/Shared/Lab_Data"
dir_project <- "/Users/ddpham/Desktop/HCP-AC"

# Where the AC results were saved
# dir_ac1 <- file.path(dir_project, "AC1")
# dir_agg <- file.path(dir_project, "AC1_agg")
dir_lm <- file.path(dir_project, "AC1_lm")
dir_plt <- file.path(dir_project, "AC1_plots")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")

cii <- read_cifti("/Users/Shared/Lab_Data/HCP_GAMBLING/103818/MNINonLinear/Results/tfMRI_GAMBLING_LR/tfMRI_GAMBLING_LR_Atlas.dtseries.nii")
cii <- select_xifti(cii, rep(1, 10))
cii$meta$cifti["intent"] <- list(3006)
cii$meta$cifti[c("time_start", "time_step", "time_unit")] <- NULL
```

```{r}
nVox <- 59412

time <- Sys.time()
for (meas in c("var", "acf1", "ar6c", "ar6v", "aic")) {
  cat(meas, "\t")
  
  q <- readRDS(file.path(dir_lm, paste0(meas, ".rds")))
  cii <- newdata_xifti(cii, q$fixed_fx, colnames(q$fixed_fx))

  for (ii in seq(colnames(q$fixed_fx))) { view_xifti_surface(cii, idx=ii, title=paste(meas, colnames(q$fixed_fx)[ii], sep=" "), fname=file.path(dir_plt, paste(meas, colnames(q$fixed_fx)[ii], sep="_"))) }
  cat("\n")
  print(Sys.time() - time); time <- Sys.time()
}
```
