---
title: "4_Visualize_LMM_AC_Stats"
author: "fatma parlak"
date: "2/10/2022"
output: html_document
---



```{r}
dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper"

dir_agg <- file.path(dir_project, "AC1_agg") # [FP:we are not calling this directory, we could remove this line]
dir_lmm <- file.path(dir_project, "AC1_lmm")
dir_plots <- file.path(dir_project, "AC1_plots")

wb_path <- "~/Desktop/workbench"
cii_tmp <- "/Volumes/Lab_Data_Drive/data/HCP_GAMBLING/103818/MNINonLinear/Results/tfMRI_GAMBLING_LR/tfMRI_GAMBLING_LR_Atlas.dtseries.nii"

# dir_project <- "/Volumes/GoogleDrive/My Drive/MEJIA_LAB_Fatma/Projects/Prewhitening_Paper" # Fatma's personal
# dir_lmm <- file.path(dir_project, "code" ,"AC1_lmm") # Fatma's personal
# dir_plots <- file.path(dir_project, "code", "AC1_plots") # Fatma's personal
# wb_path <- "~/Documents/workbench" # Fatma
# cii_tmp <- "/Volumes/GoogleDrive/My Drive/MEJIA_LAB_Fatma/Projects/Prewhitening_Paper/data/tfMRI_GAMBLING_LR_Atlas.dtseries.nii"

# Setup ---------------------------------------------------------------------------------

library(ciftiTools)
stopifnot(packageVersion("ciftiTools") >= "0.8.0")
ciftiTools.setOption("wb_path", wb_path)

tasks <- c("emotion", "gambling", "language", "motor") # , "relational", "social")
xii0 <- read_cifti(cii_tmp, idx=1, resamp_res = 6000)
xii0 <- convert_xifti(xii0, "dscalar")

n_fixed <- 9
n_random <- 8
```

```{r}
# Get experimental conditions.
iters <- expand.grid(
  pw_order=c(0, 1, 3, 6),
  pw_FWHM=c(5, Inf), 
  meas=c( "aci" , "ar6c", "var", "acf1", "ar6v")
)
iters <- subset(iters, meas=="aci")

meas <- "aci" # temp
iters_names <- paste0(meas, "_pwFWHM-", iters$pw_FWHM, "_pwO-", iters$pw_order)
iters_names2 <- paste0("FWHM ", iters$pw_FWHM, ", order ", iters$pw_order)

# Read in all the data.
dat <- vector("list", length(iters))
for (ii in seq(nrow(iters))) {
  pw_FWHM <- iters[ii, "pw_FWHM"]
  pw_order <- iters[ii, "pw_order"]
  meas <- iters[ii, "meas"]
  
  q <- readRDS(
    file.path(dir_lmm, paste0(meas, "_pwFWHM-", pw_FWHM, "_pwO-", pw_order, ".rds"))
  )
  names(q)[names(q) == "var_cor"] <- "random_fx" # [TO DO]: fix
  dat[[ii]] <- q
}

# Get coefficient names.
names_fixed <- colnames(dat[[1]]$fixed_fx)
names_random <- colnames(dat[[1]]$random_fx)[seq(n_random)]
```

### Fixed Effects

```{r eval=FALSE}
# Aggregate fixed effects by coefficient, across experimental conditions.
dat_fixed <- lapply(dat, function(x){x$fixed_fx})
dat_fixed2 <- vector("list", n_fixed)
for (nn in seq(n_fixed)) { 
  dat_fixed2[[nn]] <- do.call(cbind, lapply(dat_fixed, function(x){ x <- x[,nn] }))
  colnames(dat_fixed2[[nn]]) <- iters_names2
}
names(dat_fixed2) <- names_fixed

# Plot each fixed effect  with free zlim.
for (nn in seq(n_fixed)) {
  print(names_fixed[nn])
  xii_fx <- newdata_xifti(xii0, dat_fixed2[[nn]])
  xii_fx$meta$cifti$names <- iters_names2
  out_fname <- file.path(dir_plots, "fixed_fx", "aci", "zlim_free", names_fixed[nn])
  plot(
    xii_fx, idx=seq(8), 
    fname=out_fname, 
    together="idx", 
    together_title=names_fixed[nn], 
    title=xii_fx$meta$cifti$names
  )
}

# Manually decide the `zlim` values.
my_zlim_fe <- list(
  fixed_task = c(1.5, 3.5),
  fixed_RL = c(-.2, .2),
  fixed_cHRF = c(-.3, .3),
  fixed_task_cHRF = c(-.15, .15)
)
my_zlim2 <- c(
  rep(my_zlim_fe[1], 4),
  my_zlim_fe[2],
  my_zlim_fe[3],
  rep(my_zlim_fe[4], 3)
)

# Plot each fixed effect with the fixed zlim.
for (nn in seq(n_fixed)) {
  print(names_fixed[nn])
  xii_fx <- newdata_xifti(xii0, dat_fixed2[[nn]])
  xii_fx$meta$cifti$names <- iters_names
  out_fname <- file.path(dir_plots, "fixed_fx", "aci", "zlim_fix", names_fixed[nn])
  plot(
    xii_fx, idx = seq(8), fname=out_fname, 
    title=xii_fx$meta$cifti$names, zlim=my_zlim2[[nn]]
  )
}
```

### Random Effects

```{r}
# Aggregate random effects by coefficient, across experimental conditions.
dat_random <- lapply(dat, function(x){x$random_fx})
dat_random2 <- vector("list", n_random)
for (nn in seq(n_random)) { 
  dat_random2[[nn]] <- do.call(cbind, lapply(dat_random, function(x){ x <- x[,nn] }))
  colnames(dat_random2[[nn]]) <- iters_names2
}
names(dat_random2) <- names_random

# Plot each random effect.
for (nn in seq(n_random)) {
  print(names_random[nn])
  xii_fx <- newdata_xifti(xii0, dat_random2[[nn]])
  xii_fx$meta$cifti$names <- iters_names2
  out_fname <- file.path(dir_plots, "random_fx", "aci", "zlim_free", names_random[nn])
  plot(
    xii_fx, idx=seq(8), fname=out_fname, 
    together="idx", together_title=names_random[nn], 
    title=xii_fx$meta$cifti$names
  )
}

# Manually decide the `zlim` values.
my_zlim_re <- list(
  random_task = c(0, .4),
  random_cHRF = c(0, .1),
  random_task_cHRF = c(0, .15)
)
my_zlim2 <- c(
  rep(my_zlim_re[1], 4),
  my_zlim_re[2],
  rep(my_zlim_re[3], 3)
)

# Plot each random effect with the fixed zlim.
for (nn in seq(n_random)) {
  print(names_random[nn])
  xii_fx <- newdata_xifti(xii0, dat_random2[[nn]])
  xii_fx$meta$cifti$names <- iters_names
  out_fname <- file.path(dir_plots, "random_fx", "aci", "zlim_fix", names_random[nn])
  plot(
    xii_fx, idx=seq(8), fname=out_fname, 
    title=xii_fx$meta$cifti$names, zlim=my_zlim2[[nn]]
  )
}
```

### Differences

```{r}
dat_random3 <- lapply(dat_random2, function(x){-(x[,seq(3, 8)] - x[,1])})
# Plot each random effect with the fixed zlim.
for (nn in seq(n_random)) {
  print(names_random[nn])
  xii_fx <- newdata_xifti(xii0, dat_random3[[nn]])
  xii_fx$meta$cifti$names <- iters_names[seq(3, 8)]
  out_fname <- file.path(dir_plots, "random_fx", "aci", "diffs", "zlim_free", names_random[nn])
  plot(
    xii_fx, idx=seq(6), fname=out_fname, 
    together="idx", together_title=names_random[nn], 
    title=xii_fx$meta$cifti$names
  )
  out_fname <- file.path(dir_plots, "random_fx", "aci", "diffs", "zlim_fix", names_random[nn])
  plot(
    xii_fx, idx=seq(6), fname=out_fname,
    title=xii_fx$meta$cifti$names, zlim=my_zlim2[[nn]]
  )
}
```

