---
title: "Aggregate HCP AC Sources Results"
author: "Damon Pham"
date: "02/01/2022"
output: html_document
---

```{r}
# Setup ---------------------------------------------------------------------------------

# Directories
# dir_project <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Mac Pro
# dir_project <- "G:/.shortcut-targets-by-id/1-9kU5O4-bU0AeEZKukSvz4jbvolppJGG/ddpham/Prewhitening-Paper" # Damon personal
dir_project <- "/Volumes/Lab_Data_Drive/users/ddpham/Prewhitening-Paper"

# Where to save the first part of this analysis (this script)
dir_ac1 <- file.path(dir_project, "AC1")
dir_agg <- file.path(dir_project, "AC1_agg")

# 45 HCP retest subjects
subjects <- c(
  103818, 187547,
  105923, 192439,
  111312, 194140,
  114823, 195041,
  115320, 200109,
  122317, 200614,
  125525, 204521,
  130518, 250427,
  135528, 287248,
  137128, 341834,
  139839, 433839,
  143325, 562345,
  144226, 599671,
  146129, 601127,
  149337, 627549,
  149741, 660951,
  151526, 662551,
  158035, 783462,
  169343, 859671,
  172332, 861456,
  175439, 877168,
  177746, 917255,
  185442
)

# Remove subjects excluded from Fatma's original analysis.
subjects_rm <- c(
  144226, 627549,
  660951, 169343,
  177746
)
# 877168 has missing data for Language; see 0_Check
subjects <- setdiff(subjects, subjects_rm)

# tasks <- c("emotion", "gambling", "language", "motor", "relational", "social")
tasks <- c("emotion", "gambling", "motor", "relational")

missing <- readRDS("0_MissingFiles.rds")
missing[128,"emotion"] <- 3 #Truncated CIFTI

nVox <- 10578
```

```{r}
theVars <- list(
  task=tasks,
  subject=paste0("s", subjects),
  acquisition=c("LR", "RL"), 
  test=c("test", "retest"),
  pw_FWHM=c(5, Inf), pw_order=c(0, 1, 3, 6),
  HRF=c("HRF", "dHRF"),
  vox=seq(nVox)
)

iters <- do.call(expand.grid, rev(theVars[!(names(theVars) %in% c("HRF", "vox"))]))

# Damon 2/1/22
#   some is.na for emotion
#   none is.na for gambling

for (meas in c("var", "aci", "acit", "ar6c", "ar6v", "aic")) {
  cat(meas, "----------------\n")
  
  agg <- array(dim=vapply(theVars, length, 0))
  dimnames(agg) <- theVars
  dimnames(agg)[dimnames(agg)=="vox"] <- list(NULL)
  agg_fname <- file.path(dir_agg, paste0(meas, ".rds"))
  if (file.exists(agg_fname)) { next }
  
  # Add these results.
  time <- Sys.time()
  for (ii in seq(nrow(iters))) {

    # Prep ------------------------------------------------------------------------------
    # Get iteration info. 
    test <- iters[ii, "test"]
    test2 <- (test  == "test")
    acquisition <- as.character(iters[ii, "acquisition"])
    subject <- iters[ii, "subject"]
    subject2 <- as.numeric(gsub("s", "", subject))
    task <- iters[ii, "task"]
    pw_FWHM <- as.character(iters[ii, "pw_FWHM"])
    pw_order <- as.character(iters[ii, "pw_order"])
    ii_name <- paste0(subject2, "_", acquisition, as.numeric(test2)+1)
    ii_name <- paste0(ii_name, paste0(
      "_pwFWHM-", pw_FWHM, "_pwO-", pw_order
    ))
    cat(ii_name, "\t")

    # Skip if missing or completed already.
    missing_idx <- (missing$test == test2) & (missing$acquisition == acquisition) & (missing$subject == subject2)
    missing_idx <- which(missing_idx); stopifnot(length(missing_idx)==1)
    if (missing[missing_idx,as.character(task)] > 0) { cat("Missing data.\n"); next}    
    ac_fname <- file.path(dir_ac1, task, paste0(ii_name, ".rds"))
    if (!dir.exists(dirname(ac_fname))) { dir.create(dirname(ac_fname)) }
    if (!file.exists(ac_fname)) { stop("Missing file!\n") }
    cat("\n")
    
    cat(ii, "\t")
    # Get AC results.
    ac <- readRDS(ac_fname)
    
    if ("const" %in% names(ac)) {
      stop() # Need to check this code.
      # Get voxel mask. (Some voxels were constant and so do not have results.)
      out <- matrix(nrow=length(theVars$nreg), ncol=nVox)
      for (nn in seq(length(theVars$nreg))) { out[nn, !ac$const[[nn]]] <- ac[[nn]][[meas]] }
      agg[task, subject, acquisition, test, pw_FWHM, pw_order,,] <- out
    } else {
      agg[task, subject, acquisition, test, pw_FWHM, pw_order,,] <- do.call(rbind, lapply(ac, function(x){x[[meas]]}))
    }
  }
  saveRDS(agg, agg_fname)
  print(Sys.time() - time); time <- Sys.time()
}
```
